apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: {{ .Release.Name }}
  name: {{ .Release.Name }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: envoy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["/usr/local/bin/envoy"]
          args: ["--log-level", "debug" , "-c", "/etc/envoy-config/envoy.yaml"]
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy-config/
            - name: dynamic-data
              mountPath: /var/lib/envoy/

        - name: file-watcher
          image: "{{ .Values.imageFw.repository}}:{{ .Values.imageFw.tag}}"
          command: ["/app"]
          resources:
            requests:
              memory: "16Mi"
              cpu: "20m"
            limits:
              memory: "32Mi"
              cpu: "40m"
          volumeMounts:
            - name: envoy-lds-tpl
              mountPath: /etc/envoy/envoy-lds-tpl/
            - name: dynamic-data
              mountPath: /var/lib/envoy/
          env:
          - name: ENVOY_LDS_TPL_PATH
            value: "/etc/envoy/envoy-lds-tpl/envoy-lds.tpl"
          - name: ENVOY_LDS_OUT_PATH
            value: "/var/lib/envoy/envoy-lds.yaml"
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config
        - name: envoy-lds-tpl
          configMap:
            name: envoy-lds-tpl
        - name: dynamic-data
          emptyDir: {}

---

apiVersion: v1 
kind: Service 
metadata: 
  labels: 
    app: envoy 
  name: envoy 
  namespace: envoy
spec: 
  ports: 
  - name: 8443-8443
    port: 8443
    protocol: TCP 
    targetPort: 8443
  selector: 
    app: envoy 
  type: ClusterIP 

---
apiVersion: v1 
kind: Service 
metadata: 
  labels: 
    app: envoy
  name: app1
  namespace: envoy
spec: 
  ports: 
  - name: 8443-8443
    port: 8443
    protocol: TCP 
    targetPort: 8443
  selector: 
    app: envoy 
  type: ClusterIP 
---

apiVersion: v1 
kind: Service 
metadata: 
  labels: 
    app: envoy 
  name: prometheus 
  namespace: envoy 
spec: 
  ports: 
  - name: 9901-9901 
    port: 9901 
    protocol: TCP 
    targetPort: 9901 
  selector: 
    app: envoy 
  type: ClusterIP