apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
  namespace: envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
        - name: envoy
          image: jatrat/envoy-gateway:liam-v0.0.2 
          ports:
            - containerPort: 80
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-configmap

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-configmap
  namespace: envoy
data:
  envoy.yaml: |
    static_resources:
      listeners:
        - address:
            socket_address:
              address: 0.0.0.0
              port_value: 80
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config: 
                    "@type" : type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: http_proxy
                    route_config:
                      name: all
                      virtual_hosts:
                        - name: egress_service_http_http
                          domains:
                            - '*'
                          routes:
                            - match: { prefix: "/" }
                              route:
                                cluster: egress_service_http_http
                                prefix_rewrite: "/"
                    http_filters:
                      - name: envoy.filters.http.golang
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.Config
                          library_id: simple
                          library_path: "/lib/simple.so"
                          plugin_name: simple
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
      - name: egress_service_http_http
        connect_timeout: 2s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: egress_service_http_http
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: httpbin.org
                    port_value: 80
    admin:
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901

---

apiVersion: v1 
kind: Service 
metadata: 
  labels: 
    app: envoy 
  name: envoy 
  namespace: envoy 
spec: 
  ports: 
  - name: 80-80 
    port: 80 
    protocol: TCP 
    targetPort: 80 
  selector: 
    app: envoy 
  type: ClusterIP 

---

apiVersion: v1 
kind: Service 
metadata: 
  labels: 
    app: envoy 
  name: prometheus 
  namespace: envoy 
spec: 
  ports: 
  - name: 9901-9901 
    port: 9901 
    protocol: TCP 
    targetPort: 9901 
  selector: 
    app: envoy 
  type: ClusterIP 
